Repository ishgroup/oncourse, pull requests merged in 2022-12, with the labels that each got.

#953 OD-17728_Training_Plan_and_Timetable_dates
  client-html/src/js/containers/entities/courseClasses/components/attendance/AttendanceDayBase.tsx
  client-html/src/js/containers/entities/courseClasses/components/timetable/CourseClassTimetableTab.tsx
Labels: javascript, test-pass, test-skip

#962 OD-17716_Improved_visibility_within_the_relationship_visualiser
  client-html/src/js/containers/entities/courses/components/RelationshipView.tsx
Labels: javascript

#966 OD-17748_delete_parent_tags_fix
  client-html/src/js/containers/tags/containers/TagsFormBase.tsx
Labels: javascript, test-pass

#967 OD-17751_Student_fee_saved_incorrectly_when_clicking_Save
  client-html/src/js/containers/entities/courseClasses/components/budget/utils/index.ts
Labels: javascript, test-pass

#677 Printing borders with updated JasperReports OD-16217
  server/build.gradle
  server/src/main/java/ish/oncourse/server/print/CustomFontExtensionsRegistry.java
  server/src/main/resources/jasperreports.properties
  server/src/main/resources/reports/Enrolment/CommonwealthAssistanceNoticeReport.jrxml
  server/src/main/resources/reports/Message/MessageListReport.jrxml
Labels: test-pass
