Repository ishgroup/oncourse, pull requests merged in 2023-02, with the labels that each got.

#1005 OD-17912 Fix message `Server unavailable` in angel authentication form
  server/src/main/groovy/ish/oncourse/server/api/v1/function/UserFunctions.groovy
Labels: test-pass

#1008 OD-17924_middle_name_search_fix
  client-html/src/js/common/components/form/formFields/EditInPlaceSearchSelect.tsx
Labels: javascript, test-pass, test-skip

#1011 OD-17945_Enrolment_problem
  client-html/src/js/containers/checkout/components/payment/components/CheckoutPaymentHeaderField.tsx
  client-html/src/js/containers/entities/contacts/Contacts.tsx
  client-html/webpack.config.js
  client-html/webpack.dev.config.js
Labels: javascript

#1013 OD-17946_Improve_2FA_fields
  client-html/src/js/containers/login/LoginPage.tsx
  client-html/src/js/containers/login/components/AuthCodeDigitField.tsx
  client-html/src/js/containers/login/components/AuthCodeFieldRenderer.tsx
  client-html/src/js/containers/login/components/Credits.tsx
Labels: javascript

#1015 OD-17950_bugsnag_fix
  client-html/src/js/common/components/list-view/ListView.tsx
  client-html/src/js/common/components/list-view/components/list/ReactTableList.tsx
  client-html/src/js/containers/entities/courseClasses/components/budget/modal/TutorPayContent.tsx
Labels: test-pass

#1014 OD-17949_Class_enrolments_and_enrolled_students_are_showing_the_same_number_when_multiple_enrolments_have_occurred_over_multiple_classes
  server/src/main/groovy/ish/oncourse/server/api/v1/service/impl/EntityApiImpl.groovy
Labels: test-pass

#1018 Added ui and logic for running quotes and invoices scripts s… OD-17844
  client-html/src/js/common/components/list-view/ListView.tsx
  client-html/src/js/common/components/list-view/components/bottom-app-bar/BottomAppBar.tsx
  client-html/src/js/common/components/list-view/components/bottom-app-bar/components/ScriptsMenu.tsx
  client-html/src/js/common/components/list-view/components/list/ReactTableList.tsx
  client-html/src/js/common/epics/EpicGetScripts.ts
  client-html/src/js/containers/automation/containers/scripts/components/ExecuteScriptModal.tsx
  client-html/src/js/containers/automation/containers/scripts/components/cards/TriggerCardContent.tsx
  client-html/src/js/containers/entities/invoices/Invoices.tsx
  client-html/src/js/model/common/ListView.ts
Labels: test-pass

#1019 OD-17953_react_refs_fix
  client-html/src/js/common/components/form/formFields/EditInPlaceDateTimeField.tsx
  client-html/src/js/common/components/form/formFields/EditInPlaceField.tsx
  client-html/src/js/common/components/form/formFields/EditInPlaceFieldBase.tsx
  client-html/src/js/common/components/form/formFields/EditInPlaceQuerySelect.tsx
  client-html/src/js/common/components/form/formFields/EditInPlaceSearchSelect.tsx
  client-html/src/js/common/components/form/formFields/FormField.tsx
  client-html/src/js/common/components/form/formFields/SelectCustomComponents.tsx
  client-html/src/js/common/components/form/simpleTagListComponent/SimpleTagList.tsx
  client-html/src/js/common/components/progress/StaticProgress.tsx
  client-html/src/js/containers/automation/components/DataTypesMenu.tsx
  client-html/src/js/containers/entities/invoices/components/InvoiceLines.tsx
  client-html/src/js/containers/entities/invoices/utils/index.ts
  client-html/src/js/model/common/Fields.ts
Labels: javascript, test-pass, test-skip

#1020 OD-17787 CSP Frame support added
  client-html/webpack.config.js
Labels: javascript, test-pass
