Repository ishgroup/oncourse, pull requests merged in 2023-01, with the labels that each got.

#985 OD-17771_bugsnag_fix
  client-html/src/js/common/api/fetch-errors-handlers/InstantFetchErrorHandler.ts
  client-html/src/js/containers/dashboard/components/action-body/components/ScriptStatistic.tsx
Labels: javascript

#987 OD-17783_Invoice_notes_fix
  client-html/src/js/common/components/form/formFields/TextField.tsx
  client-html/src/js/containers/entities/invoices/Invoices.tsx
  client-html/src/js/containers/login/services/LoginServiceErrorsHandler.ts
Labels: javascript

#991 feat: loading of custom fonts from .otf files in fonts folder OD-17789
  server/src/main/java/ish/oncourse/server/print/CustomFontExtensionsRegistry.java
Labels: test-pass

#988 fix: add check if user without scratch codes with allowed TF… OD-17776
  server/src/main/groovy/ish/oncourse/server/api/v1/function/AuthenticationFunctions.groovy
Labels: test-pass

#995 OD-17834_Issue_with_tags_to_a_contact
  client-html/src/js/common/components/form/simpleTagListComponent/SimpleTagList.tsx
Labels: javascript, test-pass

#997 OD-17838_payment_method_fix
  client-html/src/js/containers/checkout/components/payment/components/CheckoutPaymentHeaderField.tsx
Labels: javascript, test-pass, test-skip

#990 OD-17787_hotjar_adjust
  client-html/src/index-template.html
Labels: javascript
