Repository ishgroup/oncourse, pull requests merged in 2023-03, with the labels that each got.

#1023 OD-17962_bugsnag_fix
  client-html/src/js/containers/entities/bankings/components/BankingCreateView.tsx
Labels: javascript

#1029 OD-17990_email_template_bindings_fix
  client-html/package.json
  client-html/src/js/common/components/form/formFields/EditInPlaceSearchSelect.tsx
  client-html/src/js/containers/automation/components/Bindings.tsx
  client-html/yarn.lock
Labels: javascript

#1030 freeBSD_build_fix
  client-html/package.json
  client-html/yarn.lock
Labels: javascript

#1031 OD-17988_tags_input_fixes
  client-html/src/js/common/components/form/documents/components/dialogs/DocumentAddDialog.tsx
  client-html/src/js/common/components/form/documents/components/dialogs/DocumentEditDialog.tsx
  client-html/src/js/common/components/form/formFields/FormField.tsx
  client-html/src/js/common/components/form/simpleTagListComponent/SimpleTagList.tsx
  client-html/src/js/common/components/form/simpleTagListComponent/validateTagsList.ts
  client-html/src/js/model/common/Fields.ts
Labels: javascript

#1035 OD-17987_generic_get_actions_fix
  client-html/src/js/common/components/list-view/ListView.tsx
  client-html/src/js/containers/entities/common/actions/index.ts
  client-html/src/js/containers/entities/common/entityItemsService.ts
  client-html/src/js/containers/entities/contacts/Contacts.tsx
  client-html/src/js/containers/entities/contacts/actions/index.ts
  client-html/src/js/containers/entities/contacts/epics/EpicGetContact.ts
  client-html/src/js/containers/entities/courseClasses/CourseClasses.tsx
  client-html/src/js/containers/entities/sites/Sites.tsx
  client-html/src/tests/entities/invoices/Invoice.Components.test.tsx
Labels: javascript, test-pass

#1038 tfa_auto_submit_fix
  client-html/src/js/containers/login/components/AuthCodeFieldRenderer.tsx
Labels: javascript

#1043 OD-18040_new_document_tags_fix
  client-html/src/js/containers/entities/common/entityItemsService.ts
Labels: javascript, test-pass, test-skip

#1045 birthday voucher upgrade OD-18033
  server/src/main/resources/scripts/ish.script.sendBirthdayVoucher.groovy
Labels: test-pass

#1048 OD-18052_LEGACY_Text_Spacebar_not_working
  client-html/src/js/common/components/markdown-editor/FormEditor.tsx
  client-html/src/js/common/components/markdown-editor/HtmlEditor.tsx
Labels: javascript, test-pass, test-skip
